<?php

// Spanish read-only contract retained from SYS; every value comes from Laravel tables.
$estado = "CASE p.status WHEN 'completed' THEN 'pagado' WHEN 'cancelled' THEN 'anulado' ELSE 'abierto' END";
$tipo = "CASE WHEN e.id IS NULL THEN 'salon' WHEN e.delivery_type='pickup' THEN 'llevar' ELSE 'delivery' END";
$paid = \Illuminate\Support\Facades\Schema::hasColumn('orders', 'paid_at') ? 'COALESCE(p.paid_at,p.updated_at)' : 'p.updated_at';
$fecha = "DATE($paid)";
$costo = 'COALESCE((SELECT SUM(pi.quantity * COALESCE(i.cost,0)) FROM product_ingredients pi JOIN products i ON i.id=pi.ingredient_id WHERE pi.product_id=pr.id),pr.cost,0)';

$unidad = \Illuminate\Support\Facades\Schema::hasColumn('products', 'unit') ? "COALESCE(pr.unit,'und')" : "'und'";
$unidadMovimiento = str_replace('pr.', 'i.', $unidad);
$minimo = \Illuminate\Support\Facades\Schema::hasColumn('products', 'minimum_stock') ? 'pr.minimum_stock' : '5';
$vigente = \Illuminate\Support\Facades\Schema::hasColumn('products', 'deleted_at') ? ' AND pr.deleted_at IS NULL' : '';
$total = '(p.total + COALESCE(e.delivery_fee,0))';

return [
    'v_ia_sys_ventas' => ['desc' => "Pedidos reales. Ventas válidas: estado='pagado'. Fecha=paid_at (fecha de cobro; histórica estimada cuando no existía). total incluye el costo de envío; costo_envio es su desglose y no debe sumarse otra vez. subtotal es la base tributaria guardada. impuesto=igv.", 'sql' => "SELECT p.id, CONCAT('PED-',p.id) codigo, $tipo tipo, m.name mesa, z.name zona, COALESCE(c.name,p.client_name) cliente, u.name mozo, $estado estado, p.subtotal, p.discount descuento, p.igv impuesto, p.tip propina, COALESCE(e.delivery_fee,0) costo_envio, $total total, CASE p.payment_method WHEN 'cash' THEN 'efectivo' WHEN 'card' THEN 'tarjeta' ELSE p.payment_method END metodo_pago, $fecha fecha, p.created_at creado_en, CASE WHEN p.status='completed' THEN $paid END pagado_en, HOUR($paid) hora FROM orders p LEFT JOIN tables m ON m.id=p.table_id LEFT JOIN areas z ON z.id=m.area_id LEFT JOIN clients c ON c.id=p.client_id LEFT JOIN users u ON u.id=p.user_id LEFT JOIN deliveries e ON e.order_id=p.id"],
    'v_ia_sys_detalle_ventas' => ['desc' => "Líneas reales de pedidos. Más vendidos: SUM(cantidad), estado_pedido='pagado'. Costo unitario calculado desde receta actual, o costo actual del producto (no costo histórico).", 'sql' => "SELECT d.id, d.order_id pedido_id, CONCAT('PED-',p.id) codigo_pedido, $fecha fecha, $estado estado_pedido, $tipo tipo_pedido, pr.name producto, c.name categoria, pr.preparation_area estacion, d.quantity cantidad, d.price precio, d.quantity*d.price importe, $costo costo_unitario, d.quantity*(d.price-$costo) utilidad, CASE d.status WHEN 'cancelled' THEN 'anulado' ELSE d.status END estado_item, d.note nota FROM order_details d JOIN orders p ON p.id=d.order_id JOIN products pr ON pr.id=d.product_id JOIN categories c ON c.id=pr.category_id LEFT JOIN deliveries e ON e.order_id=p.id"],
    'v_ia_sys_productos' => ['desc' => 'Carta real. Costo desde receta actual o costo asignado. Activo indica si está habilitado.', 'sql' => "SELECT pr.id, pr.code codigo, pr.name nombre, c.name categoria, pr.preparation_area estacion, pr.price precio, $costo costo, pr.price-($costo) margen, IF(pr.price>0,ROUND((pr.price-($costo))/pr.price*100,1),NULL) margen_pct, pr.is_active activo FROM products pr JOIN categories c ON c.id=pr.category_id WHERE pr.is_saleable=1$vigente"],
    'v_ia_sys_insumos' => ['desc' => 'Existencias vigentes con unidad y mínimo configurados. Stock bajo compara stock con stock_minimo.', 'sql' => "SELECT pr.id, pr.name nombre, $unidad unidad, pr.stock, $minimo stock_minimo, COALESCE(pr.cost,0) costo_unitario, pr.stock*COALESCE(pr.cost,0) valor_stock, (pr.stock <= $minimo) stock_bajo, pr.is_active activo FROM products pr WHERE (pr.controls_stock=1 OR pr.is_saleable=0)$vigente"],
    'v_ia_sys_movimientos_stock' => ['desc' => 'Kardex real. type sale=sale/salida; adjustment_in=entrada; adjustment_out=salida. Cantidades originales, costo actual (no histórico). No clasificar salidas como merma sin datos.', 'sql' => "SELECT mv.id, i.name insumo, $unidadMovimiento unidad, CASE mv.type WHEN 'sale' THEN 'salida' WHEN 'adjustment_in' THEN 'entrada' WHEN 'adjustment_out' THEN 'salida' ELSE mv.type END tipo, mv.quantity cantidad, mv.quantity*COALESCE(i.cost,0) valor, mv.note motivo, DATE(mv.created_at) fecha, mv.created_at creado_en FROM inventory_logs mv JOIN products i ON i.id=mv.product_id"],
    'v_ia_sys_gastos' => ['desc' => 'Gastos operativos reales. No hay categoría registrada, por eso categoria=NULL.', 'sql' => 'SELECT id, description concepto, NULL categoria, amount monto, DATE(created_at) fecha FROM expenses'],
    'v_ia_sys_clientes' => ['desc' => 'Clientes sin datos de contacto y consumo de pedidos completados.', 'sql' => "SELECT c.id,c.name nombre,DATE(c.created_at) fecha_registro,(SELECT COUNT(*) FROM orders p WHERE p.client_id=c.id AND p.status='completed') num_compras,(SELECT COALESCE(SUM(p.total + COALESCE((SELECT SUM(delivery_fee) FROM deliveries WHERE order_id=p.id),0)),0) FROM orders p WHERE p.client_id=c.id AND p.status='completed') total_comprado,(SELECT MAX(DATE($paid)) FROM orders p WHERE p.client_id=c.id AND p.status='completed') ultima_compra FROM clients c"],
    'v_ia_sys_reservas' => ['desc' => 'Reservas reales: pendiente, confirmada, cancelada.', 'sql' => "SELECT r.id,m.name mesa,z.name zona,r.client_name cliente,r.people personas,r.reservation_time fecha_hora,DATE(r.reservation_time) fecha,CASE r.status WHEN 'pending' THEN 'pendiente' WHEN 'confirmed' THEN 'confirmada' WHEN 'cancelled' THEN 'cancelada' ELSE r.status END estado FROM reservations r LEFT JOIN tables m ON m.id=r.table_id LEFT JOIN areas z ON z.id=m.area_id"],
    'v_ia_sys_cajas' => ['desc' => 'Turnos reales de caja. Diferencia negativa=faltante.', 'sql' => "SELECT cs.id,u.name cajero,cs.opening_time apertura,cs.closing_time cierre,cs.opening_amount monto_inicial,cs.expected_amount monto_esperado,cs.closing_amount monto_final,cs.difference diferencia,CASE cs.status WHEN 'open' THEN 'abierta' ELSE 'cerrada' END estado,DATE(cs.opening_time) fecha FROM cash_registers cs JOIN users u ON u.id=cs.user_id"],
    'v_ia_sys_entregas' => ['desc' => 'Delivery/recojo. No hay timestamp de salida: minutos_entrega=NULL. Estados: por_asignar, preparando, en_camino, entregado, fallido.', 'sql' => "SELECT e.order_id pedido_id,CONCAT('PED-',p.id) codigo,$tipo tipo,e.client_name contacto,dr.name repartidor,CASE e.status WHEN 'pending' THEN 'por_asignar' WHEN 'preparing' THEN 'preparando' WHEN 'on_way' THEN 'en_camino' WHEN 'delivered' THEN 'entregado' ELSE 'fallido' END entrega_estado,e.scheduled_at hora_prometida,NULL salida_en,e.delivered_at entregado_en,NULL minutos_entrega,$estado estado_pedido,$total total,e.delivery_fee costo_envio,$fecha fecha FROM deliveries e JOIN orders p ON p.id=e.order_id LEFT JOIN delivery_drivers dr ON dr.id=e.driver_id"],
];
