document.addEventListener('DOMContentLoaded',()=>{
 if(window.__sysChatIA)return;window.__sysChatIA=true;
 const esc=t=>String(t??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
 const link=[...document.querySelectorAll('a[href]')].find(a=>a.href.includes('/ai/chat'));
 const base=link?link.href.replace(/\/$/,''):'/ai/chat',askUrl=base+'/ask',clearUrl=base+'/clear';
 const csrf=document.querySelector('meta[name="csrf-token"]')?.content||document.querySelector('input[name="_token"]')?.value||'';
 const suggestions=['¿Cuánto vendimos hoy?','¿Cuáles son los 5 platos más vendidos este mes?','¿Qué insumos tienen stock bajo?','¿Qué mozo vendió más esta semana?','¿Cómo registro una compra?'];
 let root,panel,msgs,input,sendBtn,sending=false;
 const call=async(url,opt={})=>{const r=await fetch(url,{credentials:'same-origin',headers:{Accept:'application/json','Content-Type':'application/json','X-CSRF-TOKEN':csrf,...(opt.headers||{})},...opt});const d=await r.json().catch(()=>({}));if(!r.ok||d.success===false)throw new Error(d.message||'No fue posible completar la operación.');return d};
 function bind(page){
  if(page){root=document.querySelector('.chat-page-panel');panel=root;msgs=root.querySelector('.chat-msgs');input=root.querySelector('textarea');sendBtn=root.querySelector('button[type="submit"]');msgs.querySelector('.chat-sugs').innerHTML=suggestions.map(s=>`<button type="button" class="chat-sug">${esc(s)}</button>`).join('');root.querySelector('.chat-in').onsubmit=e=>{e.preventDefault();send()};root.querySelector('.chat-in textarea').disabled=false;sendBtn.disabled=false;root.querySelector('.chat-head button').onclick=clear;msgs.onclick=e=>{const b=e.target.closest('.chat-sug');if(b){input.value=b.textContent;send()}};input.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}};input.oninput=()=>{input.style.height='auto';input.style.height=Math.min(110,input.scrollHeight)+'px'};return;}
 buildFloating();
 }
 function buildFloating(){
  const st=document.createElement('style');st.textContent=`
   #sysChatRoot{position:fixed;right:20px;bottom:20px;z-index:1045}#sysChatFab{position:relative;width:62px;height:62px;border:0;border-radius:50%;color:#fff;font-size:1.5rem;background:linear-gradient(135deg,#f97316,#c2410c);box-shadow:0 14px 30px -8px rgba(249,115,22,.7);display:grid;place-items:center;animation:sysChatFloat 2.6s ease-in-out infinite}#sysChatFab:before,#sysChatFab:after{content:"";position:absolute;inset:-5px;border:2px solid #f97316;border-radius:50%;pointer-events:none;opacity:0;animation:sysChatPulse 2.6s ease-out infinite}#sysChatFab:after{animation-delay:1.3s}
   #sysChatPanel{position:absolute;right:0;bottom:78px;width:390px;height:min(620px,calc(100dvh - 120px));border:1px solid #e3e8ef;border-radius:20px;box-shadow:0 30px 70px -20px rgba(15,23,42,.45);overflow:hidden;background:#fff;display:flex;flex-direction:column}#sysChatPanel[hidden]{display:none}.sys-chat-head{display:flex;align-items:center;gap:10px;padding:12px 14px;color:#fff;background:linear-gradient(120deg,#111827,#1f2937 55%,#c2410c)}.sys-chat-head b{display:block}.sys-chat-head small{opacity:.8;display:block}.sys-chat-head button{border:0;background:rgba(255,255,255,.15);color:#fff;border-radius:9px;width:32px;height:32px}.sys-chat-av{width:36px;height:36px;border-radius:12px;background:rgba(255,255,255,.2);display:grid;place-items:center}.sys-chat-msgs{flex:1;overflow-y:auto;padding:14px;background:#f4f7fb;display:flex;flex-direction:column;gap:10px}.sys-chat-m{display:flex}.sys-chat-m.me{justify-content:flex-end}.sys-chat-b{max-width:88%;padding:9px 13px;border-radius:16px;font-size:.88rem;line-height:1.45}.sys-chat-m.bot .sys-chat-b{background:#fff;border:1px solid #e3e8ef;border-bottom-left-radius:5px}.sys-chat-m.me .sys-chat-b{background:linear-gradient(135deg,#f97316,#c2410c);color:#fff;border-bottom-right-radius:5px}.sys-chat-sugs{display:flex;flex-wrap:wrap;gap:6px}.sys-chat-sug{border:1px solid #e3e8ef;background:#fff;border-radius:999px;padding:5px 11px;font-size:.78rem}.sys-chat-in{display:flex;gap:8px;padding:10px;border-top:1px solid #e3e8ef;background:#fff}.sys-chat-in textarea{flex:1;resize:none;border:1px solid #e3e8ef;border-radius:12px;padding:.55rem .75rem;font-size:16px;background:#f4f7fb}.sys-chat-in button{width:42px;height:42px;border:0;border-radius:12px;color:#fff;background:linear-gradient(135deg,#f97316,#c2410c)}@keyframes sysChatFloat{0%,100%{transform:translateY(0)}50%{transform:translateY(-5px)}}@keyframes sysChatPulse{0%{transform:scale(.95);opacity:.55}70%{transform:scale(1.15);opacity:0}100%{opacity:0}}@media(max-width:575px){#sysChatRoot{right:14px;bottom:16px}#sysChatFab{width:54px;height:54px}#sysChatPanel{position:fixed;inset:0;width:auto;height:auto;border-radius:0}}
  `;document.head.appendChild(st);root=document.createElement('div');root.id='sysChatRoot';root.innerHTML='<div id="sysChatPanel" hidden><div class="sys-chat-head"><div class="sys-chat-av"><i class="bi bi-stars"></i></div><div class="flex-grow-1"><b>Asistente</b><small>Pregúntame sobre tu restaurante</small></div><button id="sysChatClose"><i class="bi bi-x-lg"></i></button></div><div class="sys-chat-msgs" id="sysChatMsgs"></div><form class="sys-chat-in" id="sysChatForm"><textarea id="sysChatInput" rows="1" maxlength="400" placeholder="Escribe tu pregunta…"></textarea><button><i class="bi bi-send-fill"></i></button></form></div><button id="sysChatFab"><i class="bi bi-chat-dots-fill"></i></button>';document.body.appendChild(root);panel=root.querySelector('#sysChatPanel');msgs=root.querySelector('#sysChatMsgs');input=root.querySelector('#sysChatInput');sendBtn=root.querySelector('.sys-chat-in button');root.querySelector('#sysChatFab').onclick=()=>{panel.hidden=false;setTimeout(()=>input.focus(),50)};root.querySelector('#sysChatClose').onclick=()=>panel.hidden=true;root.querySelector('#sysChatForm').onsubmit=e=>{e.preventDefault();send()};input.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}};msgs.onclick=e=>{const b=e.target.closest('.sys-chat-sug');if(b){input.value=b.textContent;send()}};add('bot','Hola. Puedo ayudarte a consultar la información de tu restaurante.');suggestionsFloating();}
 function add(type,text){const d=document.createElement('div');d.className=(root.id==='sysChatRoot'?'sys-chat-m':'chat-m')+' '+(type==='user'?'me':'bot');const b=document.createElement('div');b.className=root.id==='sysChatRoot'?'sys-chat-b':'chat-b';b.textContent=text;d.appendChild(b);msgs.appendChild(d);msgs.scrollTop=msgs.scrollHeight;return b}
 function suggestionsFloating(){const d=document.createElement('div');d.className='sys-chat-sugs';d.innerHTML=suggestions.map(s=>`<button class="sys-chat-sug" type="button">${esc(s)}</button>`).join('');msgs.appendChild(d)}
 function table(d,sys){const rows=d.data||[],cols=d.columns||(rows.length?Object.keys(rows[0]):[]);if(!rows.length)return '';return '<button class="'+(sys?'sys-chat-tg':'chat-tg')+'">Ver datos ('+rows.length+')</button><div class="'+(sys?'sys-chat-tbl':'chat-tbl')+'" hidden><table><thead><tr>'+cols.map(c=>'<th>'+esc(c.replace(/_/g,' '))+'</th>').join('')+'</tr></thead><tbody>'+rows.slice(0,10).map(r=>'<tr>'+cols.map(c=>'<td>'+esc(r[c]??'—')+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>'}
 async function send(){const m=input.value.trim();if(!m||sending)return;sending=true;msgs.querySelector('.sys-chat-sugs,.chat-sugs')?.remove();add('user',m);input.value='';const b=add('bot','');b.innerHTML=root.id==='sysChatRoot'?'<span class="sys-chat-dots">…</span>':'<span class="sys-chat-dots">…</span>';try{const r=await call(askUrl,{method:'POST',body:JSON.stringify({message:m})});b.innerHTML=esc(r.answer||'No obtuve una respuesta.')+table(r,root.id==='sysChatRoot')}catch(e){b.innerHTML='<span class="text-danger">'+esc(e.message)+'</span>'}finally{sending=false;input.focus();msgs.scrollTop=msgs.scrollHeight}}
 const page=!!document.querySelector('.chat-page-panel');bind(page);
});