@extends('layouts.app')
@section('content')
<style>
.chat-sys-page .page-head{display:flex;justify-content:space-between;align-items:flex-start;gap:16px;margin-bottom:18px}.chat-sys-page .page-head h1{font-size:1.55rem;font-weight:800;margin:0}.chat-sys-page .page-head p{margin:2px 0 0;color:#66809e}.chat-sys-page .ia-btn{border:1px solid #e3e8ef;background:#fff;border-radius:13px;padding:10px 16px;font-weight:700}
.chat-page-panel{height:calc(100dvh - 220px);min-height:460px;max-width:1080px;border:1px solid #e3e8ef;border-radius:18px;overflow:hidden;box-shadow:0 8px 30px -18px rgba(15,23,42,.4);display:flex;flex-direction:column;background:#fff}
.chat-head{display:flex;align-items:center;gap:10px;padding:14px;color:#fff;background:linear-gradient(120deg,#111827,#1f2937 55%,#c2410c)}.chat-av{width:40px;height:40px;border-radius:12px;background:rgba(255,255,255,.2);display:grid;place-items:center}.chat-head b{display:block}.chat-head small{opacity:.8;display:block}.chat-head button{border:0;background:rgba(255,255,255,.15);color:#fff;border-radius:9px;width:34px;height:34px}
.chat-msgs{flex:1;overflow-y:auto;padding:18px;background:#f4f7fb;display:flex;flex-direction:column;gap:10px}.chat-m{display:flex}.chat-m.me{justify-content:flex-end}.chat-b{max-width:88%;padding:10px 14px;border-radius:16px;font-size:.9rem;line-height:1.45;word-break:break-word}.chat-m.bot .chat-b{background:#fff;border:1px solid #e3e8ef;border-bottom-left-radius:5px}.chat-m.me .chat-b{background:linear-gradient(135deg,#f97316,#c2410c);color:#fff;border-bottom-right-radius:5px}.chat-sugs{display:flex;flex-wrap:wrap;gap:7px}.chat-sug{border:1px solid #e3e8ef;background:#fff;border-radius:999px;padding:6px 12px;font-size:.78rem;color:#0f172a}.chat-tbl{margin-top:7px;border:1px solid #e3e8ef;border-radius:10px;overflow:auto}.chat-tbl table{width:100%;font-size:.75rem}.chat-tbl th,.chat-tbl td{padding:.4rem .5rem}.chat-in{display:flex;gap:8px;padding:10px;border-top:1px solid #e3e8ef;background:#fff;align-items:flex-end}.chat-in textarea{flex:1;resize:none;border:1px solid #e3e8ef;border-radius:12px;padding:.6rem .75rem;font-size:16px;background:#f4f7fb;outline:0;max-height:110px}.chat-in textarea:focus{border-color:#f97316}.chat-in button{width:44px;height:44px;border:0;border-radius:12px;color:#fff;background:linear-gradient(135deg,#f97316,#c2410c)}
@media(max-width:768px){.chat-sys-page .page-head{flex-direction:column}.chat-page-panel{height:calc(100dvh - 190px);min-height:430px}}
</style>
<div class="chat-sys-page container-fluid">
 <div class="page-head"><div><h1>Chat IA</h1><p>Conversa con tu sistema: pregunta por ventas, platos, insumos, compras, clientes o cómo usar cada módulo</p></div><a class="ia-btn" href="{{ route('ai.assistant') }}#configurar"><i class="bi bi-gear me-1"></i> Configurar IA</a></div>
 <div class="chat-page-panel">
  <div class="chat-head"><div class="chat-av"><i class="bi bi-stars"></i></div><div class="flex-grow-1"><b>Asistente</b><small>Asistente de tu restaurante</small></div><button type="button" onclick="location.reload()" title="Nueva conversación"><i class="bi bi-arrow-counterclockwise"></i></button></div>
  <div class="chat-msgs"><div class="chat-m bot"><div class="chat-b">¡Hola! Soy el asistente de tu restaurante. Puedo consultar ventas, platos, insumos, compras, clientes y gastos, o explicarte cómo usar el sistema.</div></div><div class="chat-sugs"></div></div>
  <form class="chat-in">@csrf<textarea rows="1" maxlength="400" placeholder="Escribe tu pregunta…" disabled></textarea><button type="button" disabled><i class="bi bi-send-fill"></i></button></form>
 </div>
</div>
@endsection