<div class="modal fade" id="mdlCfg" tabindex="-1"><div class="modal-dialog modal-dialog-centered modal-lg"><div class="modal-content border-0" style="border-radius:20px">
 <form id="frmCfg" novalidate><div class="modal-header border-0 pb-0 px-4 pt-4"><h5 class="modal-title fw-bold"><i class="bi bi-gear me-2"></i>Configurar la IA</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div>
 <div class="modal-body px-4"><div class="row g-3">
  <div class="col-12"><label class="form-label">Proveedor</label><select class="form-select" name="proveedor" id="cProv"></select><div class="form-text" id="cAyuda"></div></div>
  <div class="col-md-7"><label class="form-label">URL de la API</label><input class="form-control" name="url" id="cUrl" autocomplete="off"><div class="form-text">Esta dirección conecta el sistema con el proveedor; no es una página web. Usa «Probar conexión» para verificarla. Puedes pegar la URL base o la dirección completa de chat/completions.</div></div>
  <div class="col-md-5"><label class="form-label">Modelo</label><input class="form-control" name="modelo" id="cMod" autocomplete="off"></div>
  <div class="col-12"><label class="form-label">Clave (API key)</label><input type="password" class="form-control" name="clave" id="cKey" autocomplete="new-password"><div class="form-text" id="cKeyH"></div></div>
  <div class="col-12"><div class="form-check form-switch"><input class="form-check-input" type="checkbox" name="resumen" id="cRes"><label class="form-check-label" for="cRes">Generar un resumen en lenguaje natural de cada resultado (usa una segunda consulta a la IA)</label></div></div>
  <div class="col-12"><div class="ia-privacy small mb-0"><i class="bi bi-shield-lock me-1"></i><b>Privacidad y seguridad.</b> La IA solo ve la estructura de unas vistas de lectura (sin contraseñas ni usuarios) y su consulta se valida antes de ejecutarse: solo SELECT, en modo lectura, con límite de tiempo y de filas. Al proveedor se envía tu pregunta y, si activas el resumen, hasta 25 filas del resultado (pueden incluir nombres de platos o clientes). Con <b>Ollama</b> nada sale de tu PC. La clave se guarda cifrada.</div></div>
  <div class="col-12 text-danger small" id="cErr"></div></div></div>
 <div class="modal-footer border-0 px-4 pb-4"><button type="button" class="btn btn-light me-auto" id="cTest"><i class="bi bi-plug"></i> Probar conexión</button><button type="button" class="btn btn-light" data-bs-dismiss="modal">Cerrar</button><button class="btn btn-accent px-3" id="cSave"><i class="bi bi-check2"></i> Guardar</button></div></form></div></div></div>

